//localhost

GET http://localhost:8080/contacts/ 
###

GET http://localhost:8080/contacts/65b55e340d60a0ef35a31c3c

###
 

### create contact

POST http://localhost:8080/contacts HTTP/1.1
content-type: application/json

{
    "firstName": "Chettra something",
    "lastName": "LY",
    "email": "Chettra@test.com",
    "favoriteColor": "Purple",
    "birthday": "07/12/10"
}

### update contact
PUT http://localhost:8080/contacts/65b5e5f5de0772405d9b10dd HTTP/1.1
Content-Type: application/json

{
    "firstName": "Clever",
    "lastName": "LY",
    "email": "Chettra@test.com",
    "favoriteColor": "Purple",
    "birthday": "07/12/10"
}

### delete contact
DELETE http://localhost:8080/contacts/65b5ec819ee575863cf63da2





//Production Deploy
 
### All contacts

GET https://cse341-ly.onrender.com/contacts  
###

GET https://cse341-ly.onrender.com/contacts/65b55e340d60a0ef35a31c3c

### Create New contact
POST https://cse341-ly.onrender.com/contacts  HTTP/1.1
content-type: application/json

{
    "firstName": "Chettra Post1",
    "lastName": "LY-Send to Render",
    "email": "Chettra@test.com",
    "favoriteColor": "Purple",
    "birthday": "07/12/10"
}

### update contact
PUT https://cse341-ly.onrender.com/contacts/65b5e5f5de0772405d9b10dd  HTTP/1.1
Content-Type: application/json

{
    "firstName": "Chettra put",
    "lastName": "LY",
    "email": "Chettra@test.com",
    "favoriteColor": "Purple",
    "birthday": "07/12/10"
}
 
### delete contact
DELETE https://cse341-ly.onrender.com/contacts/65b5f3249a71e8860bbb2235